#!/bin/bash
#
# Upload contents, resources, and custom.less using atmotool
#
# USAGE
# ./uploadall [config_file]
#
# config_file defaults to local.conf

## This is your prefix
PREFIX=<%= props.lcCompanyName %>

## This checks for a config argument
CONF="local.conf"
if [[ ! -z "$1" ]]
  then
    CONF="${1}"
fi
if [[ ! -e ${CONF} ]]
  then
    echo "Can't find ${CONF}"
    exit 1
fi
CONFIG="--config ${CONF}"

atmotool zip --prefix ${PREFIX} content/home/landing 
atmotool zip --prefix ${PREFIX} resources/theme/default 
atmotool upload file --path /content/home/landing ${PREFIX}_content-home-landing.zip ${CONFIG}
atmotool upload file --path /resources/theme/default ${PREFIX}_resources-theme-default.zip ${CONFIG}
atmotool upload less custom.less ${CONFIG}
